wildberries:
  status: false
  base-url: "https://static-basket-01.wbbasket.ru"
  catalog-url: "/vol0/data/main-menu-ru-ru-v3.json"
  user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0)"
  catalog-wb-url: "https://catalog.wb.ru/catalog/"
  retry-attempts: 5
  retry-delay: 1000
  shard: "electronic15"
  laptop-url: "/catalog"