ozon-parser:
  enabled: ${OZON_PARSER_ENABLED:true}
  max-threads: ${OZON_PARSER_MAX_PROCESSING_THREADS:1}
  catalog:
    cron: ${OZON_PARSER_CATALOG_CRON:0 0 * * * *}
  characteristics:
    cron: ${OZON_PARSER_CHARACTERISTICS_CRON:0 30 * * * *}