ozon-parser:
  enabled: ${OZON_PARSER_ENABLED:true}
  max-threads: ${OZON_PARSER_MAX_PROCESSING_THREADS:1}
  web-driver-url:
    catalog: ${OZON_PARSER_WEB_DRIVER_URL_CATALOG}
    characteristics: ${OZON_PARSER_WEB_DRIVER_URL_CHARACTERISTICS}
  mode: ${OZON_PARSER_MODE:headless} # visible|headless